-- =========================================================
-- Reemplazo completo de movimientos por los de Julio 2026
-- Ejecutar en: Supabase Dashboard -> SQL Editor -> New query
--
-- Este script:
--   1) Borra TODOS los movimientos existentes (gastos e ingresos)
--   2) Actualiza el saldo inicial del household al saldo de arranque de Julio
--   3) Inserta los 151 movimientos de Julio 2026 tal como figuran en la planilla
--
-- Asume un solo household en la tabla `households` (el caso de esta app).
-- Asume que existe un perfil con display_name = 'Luis' (ajustar si hace falta).
-- =========================================================

begin;

-- 1) Borrar todos los movimientos existentes
delete from movimientos where household_id = (select id from households limit 1);

-- 2) Setear el saldo inicial al de arranque de Julio 2026
update households set saldo_inicial = 84777.26, saldo_inicial_fecha = '2026-07-01'
  where id = (select id from households limit 1);

-- 3) Insertar los movimientos de Julio 2026
insert into movimientos (id, household_id, fecha, categoria, detalle, monto, tipo, created_by, created_by_nombre, updated_at, deleted)
values
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Rendimientos MP', 'Luis', 41576.56, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Rendimientos MP', 'Euge', 5188.74, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Rendimientos Personal Pay', '', 40.18, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Rendimientos Naranja X', 'Luis', 7853.82, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Rendimientos Naranja X', 'Euge', 179.8, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Sueldo', 'GlobalLogic', 4912110.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Supermercado', '', 339907.06, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Carnicería', '', 22243.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Verdulería', '', 4400.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-01', 'Venta USDT', '', 2329458.44, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-02', 'Reintegros', 'Modo', 17354.59, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-02', 'Pagos Inés', 'Flow', 81741.2, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-02', 'Pagos Inés', 'Movistar', 24302.29, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-02', 'Salidas', 'Propina', 5000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Cafetería', '', 7100.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Obra Tandil', 'Materiales Tandil', 261000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Obra Tandil', 'Matelec', 389590.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Obra Tandil', 'Sanitarios', 480680.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Restaurantes', '', 19200.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Obra Tandil', 'Arquitectas', 3500000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Almacén', '', 31650.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Panadería', '', 1400.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Supermercado', '', 18000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Cobros Factura Cammisa', '', 5600000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Salidas', '', 8500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Verdulería', '', 9000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-03', 'Reintegros', 'BNA', 13000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Aysa', '', 48225.27, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Obra Tandil', 'Volquete', 87400.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Tenis de Mesa', '', 60000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Poveda', 'Fondo mensual', 10000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Devolución Regalo Joaco', 'Kari - Agus', 60000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Ferretería', '', 66000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Almuerzo Tandil', '', 45600.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Supermercado', '', 59100.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-04', 'Materiales Calefacción', '', 661000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-05', 'Panadería', '', 12000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-05', 'Salidas', 'Restaurant', 35800.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-05', 'Movistar Euge', '', 24389.99, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-05', 'Alquiler Casa', 'Obra Tandil', 230000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-05', 'Comida', 'Otra Casa', 28000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Verdulería', '', 10600.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Cafetería', '', 7700.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Poveda', '', 684694.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Personal Flow', '', 90198.79, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Personal Flow', '', 7000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Pagos Inés', 'Camuzzi', 23384.58, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Obra Tandil', 'Calefacción', 900000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-06', 'Lentes Euge', '', 98500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-07', 'Sube', '', 2000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-07', 'Supermercado', '', 36363.23, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-07', 'Granja', 'Huevos', 5600.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-07', 'Reintegros', 'Swiss Medical', 86458.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Natación', '', 66600.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Supermercado', '', 29083.27, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Devolución Cammisa', '', 1770000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Casa', 'Expensas', 630050.09, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Auto', 'Patente', 58630.5, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Comida', 'Trabajo', 30000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Perfumeria', '', 4650.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Peluquería', '', 24000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Bares', '', 212000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Bares', '', 159000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'BNA', 'Comisión paquetes', 23922.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'BNA', 'IVA', 5023.62, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Auto', 'Combustible', 235028.91, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Seguro', '', 12481.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Lavarropas', 'Cuota 2/12', 87499.91, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-08', 'Cabify', '', 35193.76, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-09', 'Supermercado', '', 178195.28, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-09', 'Propina', '', 2000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Havanna', '', 11300.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Verdulería', '', 9890.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Carnicería', '', 32487.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Obra Tandil', 'Electricidad', 700000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Pagos Inés', 'OSSE Inés', 47279.34, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Pagos Inés', 'Municipal MDP', 38391.04, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-10', 'Pagos Inés', 'Edea Inés', 88339.12, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-11', 'Verdulería', '', 780.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-11', 'Psicologa', '', 47000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-11', 'Cafetería', '', 23000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-11', 'Jugueteria', '', 17900.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-11', 'Especias', '', 2740.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-12', 'Golfito', '', 44700.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-12', 'Havanna', '', 11300.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Usina', '', 10210.8, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Venta USDT', '', 3665169.15, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Pago Wefoc', 'Universal', 1389308.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Agua Tandil', '', 30550.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Perfumería', 'El Principito', 40000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Perfumería', 'El Principito', 12000.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Auto', 'Estacionamiento', 5400.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Impuestos sellos', '', 1488.4, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'IIBB', '', 1256.12, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'IVA', '', 13189.26, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'AFIP 30%', '', 12905.16, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Devolución', '', 12767.58, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'Carrefour 12/12', 51583.33, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'Rossi e Rossi 2/3', 98265.8, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'Carrefour 4/6', 77833.35, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'Óptica 1/3', 31333.34, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'El Principito', 103303.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'El Principito', 12003.8, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Recitales', 'Cosquín Rock 12/12', 53333.33, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Gimnasio', 'On Fit (4/6)', 67485.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Seguro Viaje', 'Luis Cuota 4/12', 9491.83, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Indumentaria Euge', 'Shivelle 3/3', 37800.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Regalo Amigos', 'Vanina 2/3', 28996.66, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Regalo Familia', 'Joaquín 2/6', 23333.16, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Indumentaria Euge', 'Cuota 2/3', 47333.33, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Calzado Euge', 'Cuota 1/3', 52666.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Auto', 'Peajes', 35604.33, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Cabify', '', 6134.41, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Cine', '', 44350.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Smiles', '', 6000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Familia', 'Regalo Joaquín', 119658.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Ruta', 'Café', 17500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Ruta', 'Almuerzo', 47000.2, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Calzado Joaquín', 'Cuota 1/6', 15499.7, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Auto', 'Combustible', 15300.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Pollería', '', 36400.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Supermercado', '', 24272.5, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Boca', 'Cuota', 44000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Boca', 'Cuota', 8520.0, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Recitales', '', 190000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Movistar Arena', 'Servicio compra', 28500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Auto', 'Seguro', 151563.73, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Gimnasio', 'Luis Megatlon', 38496.5, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Nivel 6', 'Disney', 20990.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Smiles', '', 6000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Impuestos Sellos', '', 18762.95, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'DB.RG 30%', '', 8929.53, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'IIBB', '', 595.3, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'IVA', '', 6250.67, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Obra Tandil', 'Inspección de gas', 150000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Obra Tandil', 'Hormigón carpeta', 1545406.5, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Panadería', '', 5300.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Préstamo Caro', 'Extractor 2/3', 84596.33, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Regalo Luis', 'Cuota 1/12', 23333.25, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Grifería', 'Cuota 1/3', 102606.67, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Impuestos Sellos', '', 2526.44, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Pilas', 'Cuota 2/3', 24587.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Salidas', 'Restaurant', 85800.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-13', 'Café', '', 5500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Casa', 'Crédito', 1021976.93, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Granja', '', 6500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Farmacia', '', 1177.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Librería', '', 1500.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Verdulería', '', 6250.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Venta ONs', '', 11464468.71, 'ingreso', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0),
  (uuid_generate_v4(), (select id from households limit 1), '2026-07-14', 'Pagos Universal', 'Lautaro', 405000.0, 'gasto', (select id from profiles where display_name = 'Luis' limit 1), 'Luis', now(), 0);

commit;